#!/usr/bin/env bash
#
# Derives PROPOLIS_FLEET_LISTENERS from the sensors' own bind variables and writes it to a file
# the propolis and console units load.
#
# WHY THIS EXISTS. The fleet pane needs to know which listeners are supposed to exist, and nothing
# on the control plane can discover that: no sensor has a compiled-in port, the daemon binds none
# of them, and every bind lives in a per-sensor env file (one systemd unit, one OS user, one env
# file per sensor). A hand-maintained second copy of the list in propolis.env would be a copy that
# drifts from the sensors it claims to describe, and the drift would be invisible - a listener
# quietly missing from the pane looks exactly like a listener that was never configured. Deriving
# it at deploy time from the same files the sensors read leaves drift possible only BETWEEN
# deploys, and a sensor whose events arrive while it is absent from the inventory shows up on the
# pane as `undeclared listener` rather than not at all.
#
# WHY A SEPARATE FILE, not an edit to propolis.env. install.sh's own header states that it never
# creates or edits an /etc/propolis/*.env file: those carry secrets (the database URL, the console
# password, vendor API keys) no script has business rewriting in place. This writes only a file it
# owns, containing one derived, non-secret value. propolis.service and console.service load it
# BEFORE their operator-owned env file, so an explicit operator setting still wins.
#
# The listener NAME is the sensor's own self-reported name, which is what lands in `event.sensor` -
# not the PROPOLIS_SENSOR_LOGS label. sensor-cred reports its five protocols individually, so its
# names are vnc/mysql/mssql/postgresql/mongodb while its log labels are cred-vnc and so on. The
# mapping lives in listeners-lib.sh, which mirrors crates/sensor-cred/src/main.rs's own table and
# is shared with config-check.sh so the inventory and the configuration check cannot disagree.
#
# Usage: fleet-listeners.sh [ENV_DIR] [OUT_FILE]
#   ENV_DIR    directory holding the sensor env files   (default /etc/propolis)
#   OUT_FILE   file to write                            (default $ENV_DIR/fleet-listeners.env)
# Environment:
#   PROPOLIS_FLEET_COLLECTOR_ID   collector id to stamp on each entry (default "local")
#
# Idempotent, and safe on a node where no sensor env file exists yet: it writes a header-only file
# and the pane then reports every check as unknown, which is the truth.

set -euo pipefail
shopt -s nullglob

ENV_DIR="${1:-/etc/propolis}"
OUT_FILE="${2:-$ENV_DIR/fleet-listeners.env}"
COLLECTOR_ID="${PROPOLIS_FLEET_COLLECTOR_ID:-local}"

# shellcheck source=deploy/listeners-lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/listeners-lib.sh"

ENTRIES=()

add_entry() {
    local sensor="$1" proto="$2" port="$3"
    case "$port" in
        '' | *[!0-9]*) return 0 ;;
    esac
    if [ "$port" -lt 1 ] || [ "$port" -gt 65535 ]; then
        return 0
    fi
    ENTRIES+=("$COLLECTOR_ID/$sensor/$proto/$port")
}

while IFS=$'\t' read -r sensor proto port _addr _var; do
    add_entry "$sensor" "$proto" "$port"
done < <(derive_listeners)

TMP_FILE="$OUT_FILE.tmp.$$"
{
    echo "# Generated by deploy/fleet-listeners.sh - do not edit."
    echo "# Derived from the sensor bind variables in $ENV_DIR at deploy time. Re-run install.sh,"
    echo "# upgrade.sh, or this script after changing a sensor's bind, or the fleet pane will"
    echo "# describe the listeners of the previous deploy."
    if [ "${#ENTRIES[@]}" -gt 0 ]; then
        printf 'PROPOLIS_FLEET_LISTENERS='
        printf '%s' "${ENTRIES[0]}"
        for entry in "${ENTRIES[@]:1}"; do
            printf ',%s' "$entry"
        done
        printf '\n'
    else
        echo "# No sensor bind variables found, so no listener inventory is asserted here. The"
        echo "# fleet pane reports every check as unknown rather than reporting nothing at all."
    fi
} >"$TMP_FILE"
chmod 0644 "$TMP_FILE"
mv -f "$TMP_FILE" "$OUT_FILE"

echo "==> wrote $OUT_FILE (${#ENTRIES[@]} listeners derived from $ENV_DIR)"
